<a href="https://colab.research.google.com/github/Walter-Mokwena/Health_Analytics/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Data = 'https://github.com/Walter-Mokwena/Health_Analytics/blob/main/HA_DS_TB_Lost.csv?raw=true'

In [3]:
df = pd.read_csv(Data, sep=';', decimal=',', on_bad_lines='skip')

In [4]:
df.head()

                 District  2018  2019  2020  2021  2022  2023   2024
0        !Kheis LM: NC084  13.0  12.7  15.6  19.7  12.4  14.7  11.50
1          A Nzo DM: DC44   8.6   5.3   6.0   6.4   6.3   8.0   7.10
2    Abaqulusi LM: KZN263   2.5   2.8   2.4   2.2   2.6   2.1   0.86
3  Alfred Duma LM: KZN238  11.4   5.7   4.1   5.2   6.1   6.7   5.50
4     Amahlathi LM: EC124   6.9   5.7   5.3   7.7  10.2   8.7   6.50

In [5]:
f'num of rows: {df.shape[0]}   number of colums: {df.shape[1]}'

'num of rows: 310   number of colums: 8'

In [6]:
df = df.iloc[:, [0, 7]]  # Creating a new data frame with Districts and their Loss to follow up rate for the year 2024

In [7]:
df.head()

                 District   2024
0        !Kheis LM: NC084  11.50
1          A Nzo DM: DC44   7.10
2    Abaqulusi LM: KZN263   0.86
3  Alfred Duma LM: KZN238   5.50
4     Amahlathi LM: EC124   6.50