<a href="https://colab.research.google.com/github/Walter-Mokwena/Health_Analytics/blob/main/tb_socioeconomic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
Data = 'https://github.com/Walter-Mokwena/Health_Analytics/blob/main/da_tb_data_2024.csv?raw=true'

In [9]:
df = pd.read_csv(Data, sep=';', decimal=',', on_bad_lines='skip')

In [10]:
df.head()

,District,2024,DS TB patients who were lost to follow up,All DS TB patients in cohort
0,!Kheis LM: NC084,11.50,15,131
1,A Nzo DM: DC44,7.10,187,2644
2,Abaqulusi LM: KZN263,0.86,6,699
3,Alfred Duma LM: KZN238,5.50,47,849
4,Amahlathi LM: EC124,6.50,43,663

In [5]:
f'num of rows: {df.shape[0]}   number of colums: {df.shape[1]}'

'num of rows: 310   number of colums: 8'

In [7]:
df.head()

                 District   2024
0        !Kheis LM: NC084  11.50
1          A Nzo DM: DC44   7.10
2    Abaqulusi LM: KZN263   0.86
3  Alfred Duma LM: KZN238   5.50
4     Amahlathi LM: EC124   6.50